name: Build Android APK (Flutter + Rust)

on:
  workflow_dispatch: {}
  push:
    branches: [ master, work-1.4.2 ]

jobs:
  android:
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always
      NDK_VERSION: 26.1.10909125   # 如需配合專案可改

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Java 17 給 AGP 8.x
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # 安裝 Android SDK（這步之後才會有 ANDROID_HOME/ANDROID_SDK_ROOT）
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 安裝必要的 SDK/NDK 並在此步驟「動態」導出環境變數
      - name: Install SDK/NDK/CMake & accept licenses
        shell: bash
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" \
                     "build-tools;34.0.0" \
                     "platforms;android-34" \
                     "ndk;${NDK_VERSION}" \
                     "cmake;3.22.1"
          # 導出環境變數給後續步驟使用
          echo "ANDROID_SDK_ROOT=${ANDROID_HOME}" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=${ANDROID_HOME}/ndk/${NDK_VERSION}" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=${ANDROID_HOME}/ndk/${NDK_VERSION}" >> $GITHUB_ENV
          echo "NDK_HOME=${ANDROID_HOME}/ndk/${NDK_VERSION}" >> $GITHUB_ENV

      # Rust 交叉編譯工具鏈
      - name: Install Rust + Android targets
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      # Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter pub get
        working-directory: flutter
        run: flutter pub get

      - name: Flutter doctor (optional)
        working-directory: flutter
        run: flutter doctor -v

      # Debug APK（快速測試）
      - name: Build debug APK
        working-directory: flutter
        run: flutter build apk --debug

      # Release APK（分 ABI）
      - name: Build release APK (split per ABI)
        working-directory: flutter
        run: flutter build apk --release --split-per-abi

      # 上傳產物
      - name: Upload debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: flutter/build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload release artifacts (per-ABI)
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: |
            flutter/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            flutter/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            flutter/build/app/outputs/flutter-apk/app-x86_64-release.apk
