name: Build Windows (Sciter)

on:
  workflow_dispatch: {}
  push:
    branches: [ master, work-1.4.2 ]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      CARGO_TERM_COLOR: always
      # 指定靜態 triplet，並讓 vcpkg-rs 也用同一個設定
      VCPKGRS_TRIPLET: x64-windows-static
      VCPKGRS_DYNAMIC: "0"
      VCPKG_DEFAULT_TRIPLET: x64-windows-static

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # 下載並 bootstrap vcpkg；偵測到 vcpkg.json 後會進入 manifest 模式
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      # ★ 修正：manifest 模式只需要執行 install，指定 triplet，不要列套件名
      - name: Install deps via vcpkg (manifest, static triplet)
        shell: powershell
        working-directory: ${{ github.workspace }}
        run: |
          $vcpkg = "$env:VCPKG_ROOT\vcpkg.exe"
          & $vcpkg install --triplet x64-windows-static
          # 可選：列一下 include 目錄確認
          if (Test-Path "$env:VCPKG_ROOT\installed\x64-windows-static\include") {
            Get-ChildItem "$env:VCPKG_ROOT\installed\x64-windows-static\include" | Select-Object -First 20
          }

      # LLVM（給 bindgen）
      - name: Install LLVM
        shell: powershell
        run: |
          choco install -y llvm
          echo "LIBCLANG_PATH=C:\Program Files\LLVM\bin" >> $env:GITHUB_ENV

      # 下載 Sciter DLL 到 debug/release
      - name: Download Sciter DLL
        shell: bash
        run: |
          curl -L -o sciter.dll https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.win/x64/sciter.dll
          mkdir -p target/debug target/release
          mv -f sciter.dll target/release/
          cp -f target/release/sciter.dll target/debug/

      - name: Build (debug)
        shell: bash
        run: cargo build

      - name: Build (release)
        shell: bash
        run: cargo build --release

      - name: Upload artifact (debug)
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-debug
          path: |
            target/debug/rustdesk.exe
            target/debug/sciter.dll

      - name: Upload artifact (release)
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-release
          path: |
            target/release/rustdesk.exe
            target/release/sciter.dll
