name: Build Windows (Sciter)

on:
  workflow_dispatch: {}
  push:
    branches: [ master, work-1.4.2 ]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      CARGO_TERM_COLOR: always
      # 讓 vcpkg-rs/linker 知道我們要 static triplet
      VCPKGRS_TRIPLET: x64-windows-static
      VCPKGRS_DYNAMIC: "0"
      VCPKG_DEFAULT_TRIPLET: x64-windows-static

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # 下載並 bootstrap vcpkg（提供 vcpkg.exe 與 VCPKG_ROOT）
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      # 明確安裝四個靜態相依（最關鍵修正）
      - name: Install codec deps via vcpkg (static)
        shell: powershell
        run: |
          $vcpkg = "$env:VCPKG_ROOT\vcpkg.exe"
          & $vcpkg install "libvpx:x64-windows-static" "libyuv:x64-windows-static" "opus:x64-windows-static" "aom:x64-windows-static"
          # 確認 include 真的在這裡（給日後除錯）
          Get-ChildItem "$env:VCPKG_ROOT\installed\x64-windows-static\include" | Select-Object -First 10

      # 安裝 LLVM 並設置 LIBCLANG_PATH（給 bindgen）
      - name: Install LLVM
        shell: powershell
        run: |
          choco install -y llvm
          echo "LIBCLANG_PATH=C:\Program Files\LLVM\bin" >> $env:GITHUB_ENV

      # 下載 Sciter DLL，放到 Debug/Release 兩個輸出資料夾
      - name: Download Sciter DLL
        shell: bash
        run: |
          curl -L -o sciter.dll https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.win/x64/sciter.dll
          mkdir -p target/debug
          mkdir -p target/release
          mv -f sciter.dll target/release/
          cp -f target/release/sciter.dll target/debug/

      - name: Build (debug)
        shell: bash
        run: cargo build

      - name: Build (release)
        shell: bash
        run: cargo build --release

      - name: Upload artifact (debug)
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-debug
          path: |
            target/debug/rustdesk.exe
            target/debug/sciter.dll

      - name: Upload artifact (release)
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-release
          path: |
            target/release/rustdesk.exe
            target/release/sciter.dll
