name: Build Windows (Sciter)

on:
  workflow_dispatch: {}
  push:
    branches: [ master, work-1.4.2 ]

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive   # 重要：RustDesk 有子模組

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # 使用 vcpkg（repo 根目錄含 vcpkg.json，會自動依 manifest 安裝）
      - name: Setup vcpkg and install deps
        uses: lukka/run-vcpkg@v11

      # 安裝 LLVM / 設定 LIBCLANG_PATH（給 bindgen 用）
      - name: Install LLVM
        run: |
          choco install -y llvm
          echo "LIBCLANG_PATH=C:\Program Files\LLVM\bin" >> $env:GITHUB_ENV
        shell: powershell

      # 下載 Sciter 動態庫（Windows 版），放到 release 目錄一起打包
      - name: Download Sciter DLL
        run: |
          curl -L -o sciter.dll https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.win/x64/sciter.dll
          mkdir -p target/release
          move sciter.dll target/release/
        shell: bash

      # 以 release 模式建置
      - name: Build (release)
        run: cargo build --release
        shell: bash

      # 上傳產物：exe + sciter.dll（放在同一資料夾即可執行）
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-release
          path: |
            target/release/rustdesk.exe
            target/release/sciter.dll
